# -*- coding: utf-8 -*-
"""Text Summarization Using Pre-trained Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKcon392WCYjGOEzD18UnwDOB1Q8Wl_q
"""

!pip install transformers datasets evaluate rouge_score -q

import os
import pandas as pd
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments
)
import evaluate

"""    max_input_length	The maximum length (in tokens) of the source document (the text you are summarizing) that the model will accept. Longer inputs will be truncated (cut off).
    
    max_target_length	The maximum length (in tokens) of the generated summary (the output) that the model is allowed to produce.
"""

model_name = 't5-small'
max_input_length = 512
max_target_length = 128
batch_size = 8
num_train_epochs = 2
output_dir = 't5-small-finetuned-summarization'

from datasets import load_dataset

data_files = {
    "train": "/content/train.csv",
    "validation": "/content/validation.csv",
    "test": "/content/test.csv"
}

# Attempt to load the original CSV files with error handling
dataset = load_dataset("csv", data_files=data_files, on_bad_lines='warn')
print(dataset)

# Handle missing values by replacing them with empty strings within the dataset
# This step is no longer necessary as the data is loaded from clean files.
# def clean_dataset(example):
#     example['article'] = str(example['article']) if example['article'] is not None else ''
#     example['highlights'] = str(example['highlights']) if example['highlights'] is not None else ''
#     return example

# dataset = dataset.map(clean_dataset)

print("---> Dataset loaded and ready")
print(dataset['train'][0])

def clean_csv_safe(path):
    # Try reading, skip broken lines, fill missing values, specify encoding
    try:
        df = pd.read_csv(path, on_bad_lines="skip", engine="python", encoding='latin-1')
        df.fillna("", inplace=True)

        # Trim to expected columns if more appear
        expected_cols = ["article", "highlights"]
        # Ensure all expected columns exist, fill with empty string if not
        for col in expected_cols:
            if col not in df.columns:
                df[col] = ""
        df = df[expected_cols]


        cleaned_path = path.replace(".csv", "_clean.csv")
        df.to_csv(cleaned_path, index=False)
        print(f"✅ Cleaned and saved: {cleaned_path} (rows={len(df)})")
        return cleaned_path
    except UnicodeDecodeError:
        print(f"UnicodeDecodeError reading {path}. Trying 'cp1252' encoding.")
        try:
            df = pd.read_csv(path, on_bad_lines="skip", engine="python", encoding='cp1252')
            df.fillna("", inplace=True)
            for col in expected_cols:
                if col not in df.columns:
                    df[col] = ""
            df = df[expected_cols]
            cleaned_path = path.replace(".csv", "_clean.csv")
            df.to_csv(cleaned_path, index=False)
            print(f"✅ Cleaned and saved: {cleaned_path} (rows={len(df)}) with cp1252 encoding")
            return cleaned_path
        except Exception as e:
            print(f"Error reading {path} with 'cp1252' encoding: {e}")
            return None
    except Exception as e:
        print(f"Error reading {path}: {e}")
        return None


train_path = clean_csv_safe("/content/train.csv")
val_path = clean_csv_safe("/content/validation.csv")
test_path = clean_csv_safe("/content/test.csv")

# Now load the cleaned CSVs into a datasets DatasetDict
from datasets import load_dataset

data_files = {}
if train_path:
    data_files["train"] = train_path
if val_path:
    data_files["validation"] = val_path
if test_path:
    data_files["test"] = test_path

if data_files:
    dataset = load_dataset("csv", data_files=data_files)
    print("\n--- DatasetDict loaded from cleaned files ---")
    print(dataset)
else:
    print("\n--- No cleaned files were successfully loaded ---")

tokenizer = AutoTokenizer.from_pretrained(model_name)

def preprocess_function(examples):
    inputs = [str(x) for x in examples["article"]]
    targets = [str(x) for x in examples["highlights"]]
    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets, max_length=max_target_length, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset["train"].column_names
)

print(tokenized_datasets)

# MODEL + DATA COLLATOR
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir=output_dir,
    eval_strategy='epoch',  # Corrected argument name
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=num_train_epochs,
    predict_with_generate=True,
    fp16=True,
    logging_steps=100,
    push_to_hub=False,
    report_to="none"  # disable wandb by default
)

rouge = evaluate.load('rouge')

"""      # replace -100 in the labels as tokenizer.pad_token_id  -> is a required step to make the loss function ignore padding tokens during training, ensuring the model only learns to predict the actual summary text.
      
      	During Seq2Seq training, the loss function ignores (does not calculate error for) tokens labeled as -100. This line ensures that the special padding tokens used to make all target sequences the same length are correctly marked with -100 so the model doesn't try to learn them as part of the output summary.



"""

# compute_metrics for Trainer uses generated text -> rouge

def postprocess_text(preds, labels):
  preds = [pred.strip() for pred in preds]
  labels = [label.strip() for label in labels]
  return preds, labels

def compute_metrics(eval_pred):
  predictions, labels = eval_pred

  # Debugging: Print predictions to inspect values
  print("Predictions during evaluation:", predictions)

  # decode
  decoded_preds = tokenizer.batch_decode(
      predictions,
      skip_special_tokens = True,
      clean_up_tokenization_spaces = True
  )

  # replace -100 in the labels as tokenizer.pad_token_id
  labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
  decoded_labels = tokenizer.batch_decode(
      labels,
      skip_special_tokens = True,
      clean_up_tokenization_spaces = True
  )

  decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

  result = rouge.compute(
      predictions = decoded_preds,
      references = decoded_labels,
      use_stemmer = True
  )

  result = {k: round(v * 100, 4) for k, v in result.items()}
  return result

trainer = Seq2SeqTrainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_datasets['train'].select(range(min(200, len(tokenized_datasets['train'])))), # select a smaller number of examples for training
    eval_dataset = tokenized_datasets['test'].select(range(min(200, len(tokenized_datasets['test'])))), # Use 'test' for evaluation during training
    tokenizer = tokenizer,
    data_collator = data_collator,
    compute_metrics = compute_metrics
)

trainer.train()

trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

from transformers import pipeline

# Load your fine-tuned model from output_dir
summarizer = pipeline(
    "summarization",
    model=output_dir,
    tokenizer=output_dir,
    framework="pt"  # or "tf" if you used TensorFlow backend
)

# Test 1️⃣ – a sample from your dataset
sample_text = dataset["test"][0]["article"]
print("Original article:\n", sample_text[:700], "...\n")

summary = summarizer(sample_text, max_length=128, min_length=30, do_sample=False)[0]['summary_text']
print("Generated summary:\n", summary)

custom_text = """
Apple Inc. unveiled the new iPhone 17 Pro Max during its annual launch event in California.
The phone introduces a titanium frame, improved battery efficiency, and a faster A19 Bionic chip.
Apple also announced new AI-powered features, including real-time translation and adaptive photography
modes that automatically adjust lighting based on scene context. Analysts predict strong early demand
despite rising prices, as Apple continues to dominate the premium smartphone market.
"""

print("Custom input:\n", custom_text)
summary = summarizer(custom_text, max_length=100, min_length=25, do_sample=False)[0]['summary_text']
print("\n Model Summary:\n", summary)